[versions]
agp = "8.13.2"
kotlin = "2.2.21"
core-ktx = "1.17.0"
junit = "4.13.2"
xposed = "82"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
